Dev
fynarfin/ph-ee-env-labs pull request #66
Opened 2022-08-16 11:00 UTC by somanath21

updated StorageClassname  from "ibmc-vpc-block-10iops-tier" to " gp2 "

2022-08-18 15:01 UTC, fynmanoj requested changes

2022-08-18 15:01 UTC, fynmanoj commented on helm/superset/values.yaml
> +    hostname: "fynarfin.io"
subdomian missing

2022-08-19 05:18 UTC, somanath21 commented on helm/superset/values.yaml
> +    hostname: "fynarfin.io"
Updated

2022-08-19 16:04 UTC, avikganguly01 approved these changes

2022-08-19 16:05 UTC, merged